### ISSUE TITLE
Deploying on rootless Podman with docker-compose file

### ISSUE THREAD

**Issue by pczern** [security-union/videocall-rs#265]
Hello,

I am trying to deploy `videocall-rs` on Podman.
Both `docker_tailwind-yew_1` and `docker_website_1` stop. Nats and Postgre containers are running.
Because I am running Podman rootless, I had to change some ports in my docker compose, please see below.

I am getting in docker_website_1 this
```
Error: 
   0: at `/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.29/src/lib.rs:47:76`
   1: `cargo metadata` exited with an error: error: manifest path `Cargo.toml` does not exist
   1: 

Location:
   /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.29/src/ext/cargo.rs:68

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Error: 
   0: at `/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.29/src/lib.rs:47:76`
   1: `cargo metadata` exited with an error: error: manifest path `Cargo.toml` does not exist
   1: 

Location:
   /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.29/src/ext/cargo.rs:68

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I am also getting when running podman compose up -d
```
Error: crun: chdir to `/app/yew-ui`: No such file or directory: OCI runtime attempted to invoke a command that was not found
Error: unable to start container "93327e31ca322b80bee2fe5310aa5ac429b817e517e73f59922f184e682e9177": crun: chdir to `/app/yew-ui`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```
and
```
Error: invalid port format - format is [[hostIP:]hostPort:]containerPort
```

my docker compose file is:
```
services:
  yew-ui:
    volumes:
      - /var/mnt/volume1/videocall-rs:/app:z
      - rustlemania-yew-ui-cargo-registry-cache:/usr/local/cargo/registry
      - rustlemania-yew-ui-cargo-git-cache:/usr/local/cargo/git
      - rustlemania-yew-ui-cargo-target-cache:/usr/local/cargo/target
      - rustlemania-yew-ui-cache:/app/yew-ui/target
    build:
      dockerfile: ../docker/Dockerfile.yew
      context: ../docker
    working_dir: /app/yew-ui
    command: bash -c "trunk serve --address 0.0.0.0 --port ${TRUNK_SERVE_PORT:-4000}"
    environment:
      - ACTIX_UI_BACKEND_URL=${ACTIX_UI_BACKEND_URL:-ws://localhost:${ACTIX_PORT:-8081}}
      - WEBTRANSPORT_HOST=${WEBTRANSPORT_HOST:-https://127.0.0.1:4433}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-4000}
      - ENABLE_OAUTH=false
      - LOGIN_URL=http://localhost:${ACTIX_PORT:-8081}/login
      - RUSTFLAGS=--cfg=web_sys_unstable_apis
      - RUST_BACKTRACE=1
      - WEBTRANSPORT_ENABLED=${WEBTRANSPORT_ENABLED:-false}
      - E2EE_ENABLED=${E2EE_ENABLED:-false}
      - USERS_ALLOWED_TO_STREAM=${USERS_ALLOWED_TO_STREAM:-}
      - CARGO_TARGET_DIR=/app/yew-ui/target
      - CARGO_INCREMENTAL=1
      - CARGO_NET_OFFLINE=false
    ports:
      - "${TRUNK_SERVE_PORT:-4000}:${TRUNK_SERVE_PORT:-4000}"
    depends_on:
      - tailwind-yew
    networks:
      - proxy-network

  tailwind-yew:
    build:
      dockerfile: ../docker/Dockerfile.tailwind
      context: ../docker
    volumes:
      - type: bind
        source: ../
        target: /app
    working_dir: /app/yew-ui
    entrypoint: ["/bin/sh", "-c"]
    command: "tailwindcss -i ./static/leptos-style.css -o ./static/tailwind.css --watch --minify"
    networks:
      - proxy-network

  website:
    volumes:
      - /var/mnt/volume1/videocall-rs:/app:z
      - rustlemania-leptos-ui-cargo-registry-cache:/usr/local/cargo/registry
      - rustlemania-leptos-ui-cargo-git-cache:/usr/local/cargo/git
      - rustlemania-leptos-ui-cargo-target-cache:/usr/local/cargo/target
      - rustlemania-leptos-ui-cache:/app/leptos-website/target
    build:
      dockerfile: ../docker/Dockerfile.website.dev
      context: ../docker
    working_dir: /app/leptos-website
    command: bash -c "cargo leptos watch"
    environment:
      - LEPTOS_SITE_ADDR="0.0.0.0:91"
      - CARGO_TARGET_DIR=/app/leptos-website/target
      - CARGO_INCREMENTAL=1
      - CARGO_NET_OFFLINE=false
    ports:
      - "9100:91"
    networks:
      - proxy-network

  websocket-api:
    build:
      dockerfile: ../docker/Dockerfile.actix
      context: ../docker
    working_dir: /app/actix-api
    command: bash -c "/app/dbmate/startup.sh && cargo watch -x \"run -r --bin websocket_server\""
    environment:
      - ACTIX_PORT=${ACTIX_PORT:-8081}
      - UI_ENDPOINT=${UI_ENDPOINT:-http://localhost:4000}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_AUTH_URL=${OAUTH_AUTH_URL}
      - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECT_URL=http://localhost:${ACTIX_PORT:-8081}/login/callback
      - RUST_LOG=debug
      - DATABASE_URL=postgres://postgres:docker@postgres:5432/actix-api-db?sslmode=disable
      - NATS_URL=nats:4222
      - CARGO_TARGET_DIR=/app/actix-api/target
      - CARGO_INCREMENTAL=1
      - CARGO_NET_OFFLINE=false
      - LOGIN_URL="" # needed for UI CI tests
      - ACTIX_UI_BACKEND_URL="" # needed for UI CI tests
      - WEBTRANSPORT_HOST="" # needed for UI CI tests
    ports:
      - "${ACTIX_PORT:-8081}:${ACTIX_PORT:-8081}"
    volumes:
      - /var/mnt/volume1/videocall-rs:/app:z
      - rustlemania-actix-web-cargo-registry-cache:/usr/local/cargo/registry
      - rustlemania-actix-web-cargo-git-cache:/usr/local/cargo/git
      - rustlemania-actix-web-cargo-target-cache:/usr/local/cargo/target
      - rustlemania-actix-web-target-cache:/app/actix-api/target
    depends_on:
      - postgres
      - nats
    networks:
      - proxy-network

  webtransport-api:
    build:
      dockerfile: ../docker/Dockerfile.actix
      context: ../docker
    working_dir: /app/actix-api
    command: bash -c "cargo watch -x \"run -r --bin webtransport_server\""
    environment:
      - RUST_LOG=info
      - NATS_URL=nats:4222
      - LISTEN_URL=0.0.0.0:4433
      - HEALTH_LISTEN_URL=0.0.0.0:5321
      - CERT_PATH=certs/localhost.pem
      - KEY_PATH=certs/localhost.key
      - CARGO_TARGET_DIR=/app/actix-api/target
      - CARGO_INCREMENTAL=1
      - CARGO_NET_OFFLINE=false
    ports:
      - "4433:4433/udp"
    volumes:
      - /var/mnt/volume1/videocall-rs:/app:z
      - rustlemania-actix-webtransport-cargo-registry-cache:/usr/local/cargo/registry
      - rustlemania-actix-webtransport-cargo-git-cache:/usr/local/cargo/git
      - rustlemania-actix-webtransport-cargo-target-cache:/usr/local/cargo/target
      - rustlemania-actix-webtransport-cache:/app/actix-api/target
    depends_on:
      - nats
    networks:
      - proxy-network

  nats:
    image: docker.io/nats
    command: "--http_port 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - proxy-network

  postgres:
    image: docker.io/postgres:12
    environment:
      POSTGRES_PASSWORD: "docker"
      PGPASSWORD: "docker"
    ports:
      - 5432
    networks:
      - proxy-network

volumes:
  rustlemania-actix-web-cargo-registry-cache:
  rustlemania-actix-web-cargo-git-cache:
  rustlemania-actix-web-cargo-target-cache:
  rustlemania-actix-web-target-cache:
  rustlemania-actix-webtransport-cargo-registry-cache:
  rustlemania-actix-webtransport-cargo-git-cache:
  rustlemania-actix-webtransport-cargo-target-cache:
  rustlemania-actix-webtransport-cache:
  rustlemania-yew-ui-cargo-registry-cache:
  rustlemania-yew-ui-cargo-git-cache:
  rustlemania-yew-ui-cargo-target-cache:
  rustlemania-yew-ui-cache:
  rustlemania-leptos-ui-cargo-registry-cache:
  rustlemania-leptos-ui-cargo-git-cache:
  rustlemania-leptos-ui-cargo-target-cache:
  rustlemania-leptos-ui-cache:
networks:
  proxy-network:
    external: true
    name: proxy-network
```
